const translations = {
  ar: {
    // General
    appNameWorker: "Nedjma Worker",
    appSloganWorker: "بوابتك لإدارة مهامك اليومية",
    appName: "Nedjma Connect",
    appSlogan: "الاتصال الأمثل لإدارة مشاريعك",
    loading: "جاري التحميل...",
    splashPreparing: "يتم تحميل البيانات",
    splashTip: "تتم مزامنة البيانات",
    today: "تاريخ اليوم",
    // Navigation
    home: "الرئيسية",
    about: "حول",
    settings: "الاعدادات",
    // Home View
    welcome: "أهلاً بك",
    welcomeSubtitle: "لوحتك لادارة العمال شركة بسرعة وذكاء",
    totalWorkers: "إجمالي العمال",
    activeWorkers: "العمال النشطين",
    updateData: "تحديث البيانات",
    feature1: "طلبات العمال",
    feature1_desc: "استلام ومراجعة الطلبات",
    feature2: "العمال",
    feature2_desc: "إدارة بيانات العمال",
    feature3: "لوحة حالة العمال",
    feature3_desc: "تصنيف نشط / غياب / عطلة",
    feature4: "تحليلات الغياب",
    feature4_desc: "تعرف على أكثر العمال غياباً",
    feature5: "عامل الشهر",
    feature5_desc: "المتميزون بالتزام كامل دون غياب",
    employeeOfMonthTitle: "عامل الشهر",
    employeeOfMonthSubtitle: "العاملون بدون أي غياب هذا الشهر",
    perfectAttendance: "التزام كامل",
    noChampionThisMonth: "لا يوجد مرشح هذا الشهر",
    committedThisMonth: "قائمة الملتزمين",
    feature6: "مؤشر دوران العمالة",
    feature6_desc: "نسبة العمال الجدد والمغادرين",
    turnoverTitle: "مؤشر دوران العمالة",
    hiredThisMonth: "تم توظيف",
    leftThisMonth: "غادر الشركة",
    stabilityRate: "معدل الاستقرار",
    adjustStats: "تعديل الأرقام",
    addHire: "+ توظيف",
    addLeft: "+ مغادرة",
    turnoverDetails: "تفاصيل دوران العمالة",
    currentMonthLabel: "الشهر الحالي",
    previousMonthLabel: "الشهر السابق",
    hiresLabel: "توظيف",
    leftLabel: "مغادرون",
    statusOverviewTitle: "لوحة حالة العمال",
    statusOverviewIntro: "راقب توزيع حالات العمال عبر ثلاث فئات رئيسية.",
    statusCategoryActive: "العمال الحاضرون",
    statusCategoryAbsent: "العمال الغائبون",
    statusCategoryVacation: "العمال في عطلة",
    statusCategoryEmpty: "لا يوجد عمال في هذا التصنيف.",
    absenceAnalyticsTitle: "لوحة تحليلات الغياب",
    absenceAnalyticsSubtitle: "مقارنة شهرية مع ملخص إجمالي",
    absenceCurrentMonth: "غيابات الشهر الحالي",
    absencePreviousMonth: "غيابات الشهر السابق",
    absenceAllTime: "إجمالي الغيابات",
    absenceTopCurrent: "الأكثر غياباً هذا الشهر",
    absenceTopPrevious: "الأكثر غياباً الشهر الماضي",
    absenceTopAllTime: "الأكثر غياباً على الإطلاق",
    absenceNoData: "لا توجد سجلات غياب بعد.",
    absenceTrendUp: "زيادة عن الشهر الماضي",
    absenceTrendDown: "انخفاض عن الشهر الماضي",
    absenceCurrentShort: "هذا الشهر",
    absencePreviousShort: "الشهر الماضي",
    absenceTotalShort: "الإجمالي",
    moreFeatures: "ميزات إضافية",
    moreFeatures_desc: "أدوات تنظيمية متقدمة",
    // Worker details (Manager)
    workerDetails: "تفاصيل العامل",
    fullName: "الاسم الكامل",
    posteLabel: "المنصب",
    phoneLabel: "رقم الهاتف",
    departmentLabel: "القسم",
    statusLabel: "الحالة",
    statusActive: "نشط",
    statusAbsent: "غائب",
    statusVacation: "في عطلة",
    statusOnVacation: "في عطلة",
    statusStopped: "متوقف",
    attendanceLog: "سجل الإحصائيات",
    updateAttendance: "تحديث السجل",
    noAttendanceYet: "لا يوجد سجل بعد.",
    balanceLabel: "الرصيد",
    performancePoints: "نقاط الأداء",
    addBonus: "إضافة مكافأة",
    deduct: "خصم",
    workerCode: "كود العامل",
    copyCode: "نسخ الكود",
    // Messaging
    sendMessage: "إرسال رسالة",
    messageWorkerTitle: "مراسلة العامل",
    messagePlaceholder: "اكتب رسالتك هنا...",
    sendNow: "إرسال الآن",
    notificationsTitle: "إشعارات الردود",
    notificationsEmpty: "لا توجد ردود جديدة حالياً.",
    markAllSeen: "وضع الكل كمقروء",
    // Requests (Worker)
    sendRequestTitle: "سجل الطلبات",
    noRequestsYet: "لم تقم بإرسال أي طلبات بعد.",
    addRequest: "إضافة طلب",
    requestDetailsTitle: "تفاصيل الطلب",
    requestType: "نوع الطلب",
    typeAbsence: "غياب",
    typeVacation: "طلب إجازة",
    typeComplaint: "شكوى",
    typeNote: "ملاحظة",
    typeDocument: "طلب وثيقة",
    requestDate: "تاريخ الطلب",
    absenceDate: "تاريخ الغياب",
    vacationStart: "بداية الإجازة",
    vacationEnd: "نهاية الإجازة",
    notes: "الملاحظة",
    notesPlaceholder: "اشرح سبب الطلب...",
    submitRequest: "إرسال الطلب",
    // Requests (Manager)
    inboxTitle: "طلبات العمال",
    noWorkerRequestsYet: "لا توجد معلومات للعمال حتى الآن.",
    // Worker Home View
    workerCard1: "إرسال طلب",
    workerCard1_desc: "إرسال طلب للإدارة",
    workerCard2: "تسجيل الحضور",
    workerCard2_desc: "متابعة أيام العمل والغياب",
    workerCard3: "محفظتي الذكية",
    workerCard3_desc: "إدارة مصاريفي الشهرية",
    workerCard4: "ملفي الشخصي",
    workerCard4_desc: "عرض معلوماتك ورصيدك",
    requestsStats: "إحصائيات الطلبات",
    requestsStats_desc: "عرض ملخص مرئي لطلباتك",
    totalRequests: "إجمالي الطلبات",
    statusPending: "قيد المراجعة",
    statusApproved: "مقبولة",
    statusRejected: "مرفوضة",
    requestsByType: "الطلبات حسب النوع",
    monthlyTrend: "توجه الطلبات الشهري",
    absenceTrendTitle: "توجه الحضور والغياب الشهري",
    legendPresent: "حضور",
    legendAbsent: "غياب",
    attendanceDetailTitle: "تفاصيل اليوم",
    checkIn: "وقت الدخول",
    checkOut: "وقت الخروج",
    // Settings View
    language: "اللغة",
    theme: "المظهر",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    themeSelectionDesc: "اختر بين الوضع الفاتح، الداكن، ومجموعة من الألوان",
    // Theme Names
    themeDefaultLight: "افتراضي",
    themeOceanLight: "محيط فاتح",
    themeForestLight: "غابة فاتحة",
    themeSunsetLight: "غروب الشمس",
    themeNeutralLight: "محايد فاتح",
    themeRoseLight: "وردي فاتح",
    themeIndigoLight: "نيلي فاتح",
    themeMintLight: "نعناع فاتح",
    themeSkyLight: "سماوي فاتح",
    themeLavenderLight: "خزامى فاتح",
    themeDefaultDark: "افتراضي داكن",
    themeSlateDark: "أردوازي داكن",
    themePurpleDark: "بنفسجي داكن",
    themeForestDark: "غابة داكنة",
    // More Features View
    moreFeaturesTitle: "ميزات إضافية",
    backToHome: "العودة للرئيسية",
    feature7: "مساعد Nedjma الذكي",
    feature7_desc: "تحليل الغياب وتوليد رسائل واقتراحات",
    aiAssistantTitle: "المساعد الذكي الإداري",
    aiAssistantIntro: "تحليلات ذكية، استشارات فورية، ورسائل احترافية",
    aiWeeklyAnalysis: "تحليل أسبوعي تلقائي",
    aiRunAnalysis: "توليد التحليل",
    aiConsultant: "المستشار الذكي",
    aiAskPlaceholder: "اكتب سؤالك الإداري هنا...",
    aiAskButton: "اسأل المساعد",
    aiMessageGen: "مولد الرسائل الإدارية",
    aiDeptLabel: "اختر القسم",
    aiDeptAll: "كل الأقسام",
    aiGenerate: "توليد رسالة",
    aiNoData: "لا توجد بيانات كافية للتحليل حالياً.",
    aiTip: "يعتمد هذا المساعد على بيانات الغياب والعمال المسجلة لديك.",
    aiSuggested: "اقتراح:",
    aiMostAbsent: "أكثر قسم يعاني من الغياب",
    aiThisWeek: "هذا الأسبوع",
    aiLastWeek: "الأسبوع الماضي",
    feature8: "معلومات مطور البرنامج",
    feature8_desc: "نبذة وصور المطور ووسيلة تواصل",
    devInfoTitle: "معلومات مطور البرنامج",
    devBioTitle: "بلال بورابعة",
    devBioText: "بلال بورابعة مطور برمجيات جزائري يتمتع بخبرة تمتد منذ عام 2014، شغوف بعالم الذكاء الاصطناعي وهندسة البرمجيات. اشتهر بلقب إمبراطور التقنية 👑 بفضل قدرته على تصميم وتطوير أنظمة وتطبيقات متقدمة تجمع بين الأداء العالي والابتكار. يتقن العمل على بيئات التطوير المختلفة مثل Android Studio وVisual Studio Code، وله بصمة مميزة في برمجة التطبيقات، الأنظمة المخصصة، وحلول الذكاء الاصطناعي. يؤمن بلال بأن البرمجة ليست مجرد كتابة أكواد، بل فنّ لبناء أفكار تُحدث فرقًا في العالم الرقمي، ويسعى دائمًا إلى مشاركة خبراته ودعم المطورين لتحقيق التفوق والإبداع في مجالاتهم.",
    sendMessageToDev: "📨 أرسل رسالة للمطور",
    devEmailLabel: "البريد الإلكتروني (اختياري)",
    devEmailPlaceholder: "example@email.com",
    devMessageLabel: "نص الرسالة",
    devMessagePlaceholder: "اكتب رسالتك هنا...",
    devSendBtn: "إرسال",
    devCancelBtn: "إلغاء",
    devSavedNotice: "تم حفظ رسالتك. سيتم التواصل قريباً.",
    feature9: "بطاقة رقم 9",
    feature9_desc: "بطاقة فارغة",
    feature10: "بطاقة رقم 10",
    feature10_desc: "بطاقة فارغة",
    feature11: "بطاقة رقم 11",
    feature11_desc: "بطاقة فارغة",
    feature12: "بطاقة رقم 12",
    feature12_desc: "بطاقة فارغة",
    // About View (Added for dynamic translation)
    aboutAppTitle: "🧠 حول تطبيق Nedjma Connect",
    aboutAppP1: "تطبيق Nedjma Connect هو منصة تنظيمية ذكية تهدف إلى تسهيل التواصل الداخلي وتحسين إدارة المهام داخل بيئة العمل.",
    aboutAppP2: "من خلال واجهة بسيطة وواضحة، يمكن للإدارة والعمال التفاعل بسرعة، تسجيل الأنشطة، ومتابعة التطورات اليومية بشكل فعّال ومنظم.",
    appVersion: "الإصدار 1.0.0",
    // Sidebar taglines
    sidebarTaglineManager: "لوحة الإدارة",
    sidebarTaglineWorker: "تطبيق العامل",
    aboutDevTitle: "بلال بورابعة",
    aboutDevSubtitle: "مطور برمجيات",
    aboutDevBio: "👨‍💻 مطور برمجيات منذ 2014، شغوف بالذكاء الاصطناعي وهندسة البرمجيات. صاحب مدونة تقنية ومؤلف كتاب حول نظام أندرويد يصدر في 2025. معروف بلقب إمبراطور التقنية، بخبرة في تطوير التطبيقات عبر Android Studio وVisual Studio Code، مع مشاريع تعليمية وإبداعية لمشاركة المعرفة ودعم المطورين.",
    contactMe: "تواصل معي",
    // Confirmation Modal
    confirmAction: "تأكيد الإجراء",
    confirmLangChange: "هل أنت متأكد من تغيير اللغة إلى {langName}؟",
    cancel: "إلغاء",
    confirm: "تأكيد",
  },
  en: {
    // General
    appNameWorker: "Nedjma Worker",
    appSloganWorker: "Your portal to manage daily tasks",
    appName: "Nedjma Connect",
    appSlogan: "The optimal connection for project management",
    loading: "Loading...",
    splashPreparing: "Loading data",
    splashTip: "Syncing team data and optimizing the workspace",
    today: "Today's Date",
    // Navigation
    home: "Dashboard",
    about: "About",
    settings: "Settings",
    // Home View
    welcome: "Welcome",
    welcomeSubtitle: "Your smart hub to manage your team",
    totalWorkers: "Total Workers",
    activeWorkers: "Active Workers",
    updateData: "Refresh Data",
    feature1: "Worker Requests",
    feature1_desc: "Receive and review requests",
    feature2: "Workers",
    feature2_desc: "Manage worker data",
    feature3: "Worker Status Board",
    feature3_desc: "Active / Absent / Vacation insights",
    feature4: "Absence Analytics",
    feature4_desc: "See who is missing the most",
    feature5: "Employee of the Month",
    feature5_desc: "Perfect attendance without any absence",
    employeeOfMonthTitle: "Employee of the Month",
    employeeOfMonthSubtitle: "Workers with zero absences this month",
    perfectAttendance: "Perfect attendance",
    noChampionThisMonth: "No champion this month",
    committedThisMonth: "Committed this month",
    feature6: "Turnover Tracker",
    feature6_desc: "New vs. departed employees",
    turnoverTitle: "Turnover Tracker",
    hiredThisMonth: "Hired",
    leftThisMonth: "Departed",
    stabilityRate: "Stability Rate",
    adjustStats: "Adjust Stats",
    addHire: "+ Hire",
    addLeft: "+ Depart",
    turnoverDetails: "Turnover Details",
    currentMonthLabel: "Current Month",
    previousMonthLabel: "Previous Month",
    hiresLabel: "Hires",
    leftLabel: "Departures",
    statusOverviewTitle: "Worker Status Board",
    statusOverviewIntro: "Track how your workforce is distributed across three status buckets.",
    statusCategoryActive: "Present workers",
    statusCategoryAbsent: "Absent workers",
    statusCategoryVacation: "On vacation",
    statusCategoryEmpty: "No workers in this category.",
    absenceAnalyticsTitle: "Absence Analytics Board",
    absenceAnalyticsSubtitle: "Monthly comparison with lifetime summary",
    absenceCurrentMonth: "Current month absences",
    absencePreviousMonth: "Last month absences",
    absenceAllTime: "Lifetime absences",
    absenceTopCurrent: "Top absentees this month",
    absenceTopPrevious: "Top absentees last month",
    absenceTopAllTime: "Most absent overall",
    absenceNoData: "No absence records yet.",
    absenceTrendUp: "Higher than last month",
    absenceTrendDown: "Lower than last month",
    absenceCurrentShort: "This month",
    absencePreviousShort: "Last month",
    absenceTotalShort: "Total",
    moreFeatures: "More Features",
    moreFeatures_desc: "Advanced organizational tools",
    // Worker details (Manager)
    workerDetails: "Worker Details",
    fullName: "Full Name",
    posteLabel: "Poste",
    phoneLabel: "Phone",
    departmentLabel: "Department",
    statusLabel: "Status",
    statusActive: "Active",
    statusAbsent: "Absent",
    statusVacation: "On Vacation",
    statusOnVacation: "On Vacation",
    statusStopped: "Stopped",
    attendanceLog: "Statistics Log",
    updateAttendance: "Update Log",
    noAttendanceYet: "No records yet.",
    balanceLabel: "Balance",
    performancePoints: "Performance Points",
    addBonus: "Add Bonus",
    deduct: "Deduct",
    workerCode: "Worker Code",
    copyCode: "Copy Code",
    // Messaging
    sendMessage: "Send Message",
    messageWorkerTitle: "Message Worker",
    messagePlaceholder: "Type your message...",
    sendNow: "Send Now",
    notificationsTitle: "Reply Notifications",
    notificationsEmpty: "No new replies right now.",
    markAllSeen: "Mark all as read",
    // Requests (Worker)
    sendRequestTitle: "Requests Log",
    noRequestsYet: "You haven't sent any requests yet.",
    addRequest: "Add Request",
    requestDetailsTitle: "Request Details",
    requestType: "Request Type",
    typeAbsence: "Absence",
    typeVacation: "Vacation Request",
    typeComplaint: "Complaint",
    typeNote: "Note",
    typeDocument: "Document Request",
    requestDate: "Request Date",
    absenceDate: "Absence Date",
    vacationStart: "Vacation Start",
    vacationEnd: "Vacation End",
    notes: "Notes",
    notesPlaceholder: "Describe the reason...",
    submitRequest: "Send Request",
    // Requests (Manager)
    inboxTitle: "Worker Requests",
    noWorkerRequestsYet: "No worker requests yet.",
    // Worker Home View
    workerCard1: "Send Request",
    workerCard1_desc: "Submit a request to management",
    workerCard2: "Attendance",
    workerCard2_desc: "Track your work and absent days",
    workerCard3: "Smart Wallet",
    workerCard3_desc: "Manage my monthly expenses",
    workerCard4: "My Profile",
    workerCard4_desc: "View your info and balance",
    requestsStats: "Requests Stats",
    requestsStats_desc: "View a visual summary of your requests",
    totalRequests: "Total Requests",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    requestsByType: "Requests by Type",
    monthlyTrend: "Monthly Request Trend",
    absenceTrendTitle: "Monthly Attendance Trend",
    legendPresent: "Present",
    legendAbsent: "Absent",
    attendanceDetailTitle: "Day Details",
    checkIn: "Check-in",
    checkOut: "Check-out",
    // Settings View
    language: "Language",
    theme: "Appearance",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    themeSelectionDesc: "Choose between light, dark, and a variety of colors",
    // Theme Names
    themeDefaultLight: "Default",
    themeOceanLight: "Ocean Light",
    themeForestLight: "Forest Light",
    themeSunsetLight: "Sunset Light",
    themeNeutralLight: "Neutral Light",
    themeRoseLight: "Rose Light",
    themeIndigoLight: "Indigo Light",
    themeMintLight: "Mint Light",
    themeSkyLight: "Sky Light",
    themeLavenderLight: "Lavender Light",
    themeDefaultDark: "Default Dark",
    themeSlateDark: "Slate Dark",
    themePurpleDark: "Purple Dark",
    themeForestDark: "Forest Dark",
    // More Features View
    moreFeaturesTitle: "Additional Features",
    backToHome: "Back to Home",
    feature7: "Nedjma AI Assistant",
    feature7_desc: "Absence analysis, suggestions, and messages",
    aiAssistantTitle: "AI Admin Assistant",
    aiAssistantIntro: "Smart analytics, instant advice, and professional messages",
    aiWeeklyAnalysis: "Weekly Automatic Analysis",
    aiRunAnalysis: "Run Analysis",
    aiConsultant: "Smart Consultant",
    aiAskPlaceholder: "Type your management question here...",
    aiAskButton: "Ask Assistant",
    aiMessageGen: "Administrative Message Generator",
    aiDeptLabel: "Choose Department",
    aiDeptAll: "All Departments",
    aiGenerate: "Generate Message",
    aiNoData: "Not enough data to analyze yet.",
    aiTip: "This assistant relies on your recorded workers and absences.",
    aiSuggested: "Suggestion:",
    aiMostAbsent: "Most absent department",
    aiThisWeek: "This week",
    aiLastWeek: "Last week",
    feature8: "Developer Info",
    feature8_desc: "Developer profile, photo and contact",
    devInfoTitle: "Developer Information",
    devBioTitle: "Billel Bouraba",
    devBioText: "Billel Bouraba is an Algerian software developer with experience since 2014, passionate about AI and software engineering. Known as the Tech Emperor 👑 for delivering advanced, high‑performance, and innovative systems and apps. Skilled with Android Studio and Visual Studio Code, with a solid footprint in app development, custom systems, and AI solutions. He believes programming is an art to build ideas that make a difference in the digital world, and he constantly shares knowledge and supports developers to achieve excellence and creativity.",
    sendMessageToDev: "📨 Send Message to Developer",
    devEmailLabel: "Email (optional)",
    devEmailPlaceholder: "example@email.com",
    devMessageLabel: "Message",
    devMessagePlaceholder: "Type your message here...",
    devSendBtn: "Send",
    devCancelBtn: "Cancel",
    devSavedNotice: "Your message has been saved. We will get back to you soon.",
    feature9: "Card No. 9",
    feature9_desc: "Empty Card",
    feature10: "Card No. 10",
    feature10_desc: "Empty Card",
    feature11: "Card No. 11",
    feature11_desc: "Empty Card",
    feature12: "Card No. 12",
    feature12_desc: "Empty Card",
    // About View (Added for dynamic translation)
    aboutAppTitle: "🧠 About Nedjma Connect",
    aboutAppP1: "Nedjma Connect is a smart organizational platform designed to facilitate internal communication and improve task management within the work environment.",
    aboutAppP2: "Through a simple and clear interface, management and workers can interact quickly, log activities, and track daily progress efficiently and in an organized manner.",
    appVersion: "Version 1.0.0",
    // Sidebar taglines
    sidebarTaglineManager: "Admin Console",
    sidebarTaglineWorker: "Worker App",
    aboutDevTitle: "Billel Bouraba",
    aboutDevSubtitle: "Software Developer",
    aboutDevBio: "👨‍💻 Software developer since 2014, passionate about AI and software engineering. Owner of a tech blog and author of a book on the Android system to be released in 2025. Known as the 'Tech Emperor', with expertise in app development using Android Studio and Visual Studio Code, with educational and creative projects to share knowledge and support developers.",
  contactMe: "Contact Me",
  // Confirmation Modal
  confirmAction: "Confirm Action",
  confirmLangChange: "Are you sure you want to change the language to {langName}?",
  cancel: "Cancel",
  confirm: "Confirm",
}
};

if (typeof window !== 'undefined') {
  window.translations = translations;
}
